# df_agent_utils.py
from langchain_groq import ChatGroq
from langchain_experimental.agents import create_pandas_dataframe_agent


def build_df_agent(df, groq_api_key, model_name="llama3-70b-8192"):
    """
    Return a Pandas-aware agent that can run analytic queries.
    NB: We set allow_dangerous_code=True because the agent executes
    arbitrary Python generated by the LLM. Make sure your hosting
    environment is sandboxed or guarded before using in production.
    """
    llm = ChatGroq(
        groq_api_key=groq_api_key,
        model_name=model_name,
        temperature=0,
    )
    return create_pandas_dataframe_agent(
        llm,
        df,
        verbose=False,
        allow_dangerous_code=True,   # ← REQUIRED flag
    )
